yarn theo ./assets/tokens/border-radius/index.yml --transform web --format scss,cssmodules.css,module.js,common.js,custom-properties.css --dest ./assets/tokens/border-radius/
yarn theo ./assets/tokens/color-background/index.yml --transform web --format scss,cssmodules.css,module.js,common.js,custom-properties.css --dest ./assets/tokens/color-background/
yarn theo ./assets/tokens/color-border/index.yml --transform web --format scss,cssmodules.css,module.js,common.js,custom-properties.css --dest ./assets/tokens/color-border/
yarn theo ./assets/tokens/color-text/index.yml --transform web --format scss,cssmodules.css,module.js,common.js,custom-properties.css --dest ./assets/tokens/color-text/
yarn theo ./assets/tokens/font/index.yml --transform web --format scss,cssmodules.css,module.js,common.js,custom-properties.css --dest ./assets/tokens/font/
yarn theo ./assets/tokens/font-size/index.yml --transform web --format scss,cssmodules.css,module.js,common.js,custom-properties.css --dest ./assets/tokens/font-size/
yarn theo ./assets/tokens/line-height/index.yml --transform web --format scss,cssmodules.css,module.js,common.js,custom-properties.css --dest ./assets/tokens/line-height/
yarn theo ./assets/tokens/spacing/index.yml --transform web --format scss,cssmodules.css,module.js,common.js,custom-properties.css --dest ./assets/tokens/spacing/
yarn theo ./assets/tokens/z-index/index.yml --transform web --format scss,cssmodules.css,module.js,common.js,custom-properties.css --dest ./assets/tokens/z-index/
yarn theo ./assets/tokens/index.yml --transform web --format scss,cssmodules.css,module.js,common.js,custom-properties.css --dest ./assets/tokens/
