version: 2.1

_defaults: &defaults
  docker:
    - image: circleci/node:12.9.0-browsers
  working_directory: ~/scbd/ecosystem
  parallelism: 1


jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - eco2-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - eco2-
      - run: pwd && yarn --version && yarn install --frozen-lockfile && $(yarn bin)/cypress install && yarn boot
      - save_cache:
          key: eco2-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/scbd
            - path: ecosystem

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/scbd/ecosystem
      - run: yarn run lint
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/scbd/ecosystem
      - run: yarn run build
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/scbd/ecosystem
      - run: alias cypress="$(yarn bin)/cypress" && yarn run test:e2e:headless

workflows:
  version: 2
  install-and-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - lint
