version: 2.1

_defaults: &defaults
  docker:
    - image: circleci/node:12.9.0-browsers
  working_directory: ~/scbd/ecosystem
  parallelism: 1


jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - eco5-{{ checksum "yarn.lock" }}
            - eco5-
      - run: pwd && yarn --version && ls -al && yarn install && yarn boot
      - save_cache:
          key: eco5-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/scbd
          paths: 
            - ecosystem

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/scbd
      - run: pwd && ls -al && yarn run lint

  audit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/scbd
      - run:
          name: Security Audit
          command: lerna exec yarn audit
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/scbd
      - run:
          name: Build package distributions
          command: yarn run build       
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/scbd
# restore_cache needed for ~/.cache ... cypress binary is stored there
      - restore_cache:  
          keys:
            - eco5-{{ checksum "yarn.lock" }}
            - eco5-
      - run:
          name: Cypress e2e tests
          command: alias cypress="$(yarn bin)/cypress" && yarn run test:e2e:headless

workflows:
  version: 2
  install-and-test:
    jobs:
      - install
      - audit:
          requires:
            - install
      - lint:
          requires:
            - audit
      - test:
          requires:
            - audit
