version: 2.1

_defaults: &defaults
  docker:
    - image: circleci/node:12.9.0-browsers
  working_directory: ~/scbd/ecosystem
  parallelism: 1


jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - ecosystem-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - ecosystem-{{ .Branch }}-
            - ecosystem-
      - run: yarn boot
      - save_cache:
          key: ecosystem-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/scbd
          paths:
            - ecosystem
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/scbd
      - run: yarn run lint
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/scbd
      - run: yarn run build
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/scbd
      - run: yarn run test:e2e:headless
workflows:
  version: 2
  install-and-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - lint